// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdELZTDPMHgclKtu00CgHzbc1VllxPjXU',
    appId: '1:914920624612:web:9c29c55c4ae15dea0137f1',
    messagingSenderId: '914920624612',
    projectId: 'zapfnavi',
    authDomain: 'zapfnavi.firebaseapp.com',
    storageBucket: 'zapfnavi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi7F9w_yY_oIQEZnVHUrBbuWPIECXmDO4',
    appId: '1:914920624612:android:6c49bb437a534ac10137f1',
    messagingSenderId: '914920624612',
    projectId: 'zapfnavi',
    storageBucket: 'zapfnavi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9_ryjpM4dYH41QwWpz6KbB5EMmClsqrg',
    appId: '1:914920624612:ios:2365b633784dd3160137f1',
    messagingSenderId: '914920624612',
    projectId: 'zapfnavi',
    storageBucket: 'zapfnavi.firebasestorage.app',
    iosBundleId: 'com.example.benzinsparren',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9_ryjpM4dYH41QwWpz6KbB5EMmClsqrg',
    appId: '1:914920624612:ios:2365b633784dd3160137f1',
    messagingSenderId: '914920624612',
    projectId: 'zapfnavi',
    storageBucket: 'zapfnavi.firebasestorage.app',
    iosBundleId: 'com.example.benzinsparren',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdELZTDPMHgclKtu00CgHzbc1VllxPjXU',
    appId: '1:914920624612:web:c832a82eb2e2d00b0137f1',
    messagingSenderId: '914920624612',
    projectId: 'zapfnavi',
    authDomain: 'zapfnavi.firebaseapp.com',
    storageBucket: 'zapfnavi.firebasestorage.app',
  );
}
